import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lyrics Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header>
        <div className='text-center p-10 text-4xl text-indigo-600 font-semibold'>
          <p className="link">generate lyrics</p>
        </div>

        <div>

        </div>
      </header>

      {/* Body */}
    </div>
  )
}
